{
 "title": "Flink Lag Dashboard",
 "time": { "from": "2023-12-14T12:16:48.449Z", "to": "2023-12-14T12:26:48.449Z" },
 "templating": {
  "list": [
   { "name": "env", "query": "ntpprod" }
  ]
 },
 "panels": [
  { "title": "KP Flink Consumer Group Lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "activity aggregate Lag",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"dev-activity-aggregate-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "program activity agreegator",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"dev-program-activity-aggregate-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "collection-cert-pre-processor Lag",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"dev-collection-cert-pre-processor-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "program cert pre-processor",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"dev-program-cert-pre-processor-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "certificate generator Lag",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"dev-certificate-generator-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "content publish Lag",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"dev-content-publish-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "questionset publish Lag",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"dev-questionset-publish-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "post publish processor Lag",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"dev-post-publish-processor-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "search indexer Lag",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"dev-search-indexer-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "relation cache updater Lag",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"dev-relation-cache-updater-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "asset enrichment lag",
   "type": "graph",
   "description": "Threshold:\nWarning: 1M\nCritical:  2M",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"dev-asset-enrichment-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "audit history indexer Lag",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"dev-audit-history-indexer-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "metrics data transformer Lag",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"dev-metrics-data-transformer-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "audit event generator lag",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"dev-audit-event-generator-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "enrolment reconciliation Lag",
   "type": "graph",
   "description": "Threshold: \nWarning: 1M\nCritical: 2M",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"dev-enrolment-reconciliation-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  { "title": "DP Flink Consumer Group Lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Ingestion Router lag",
   "type": "graph",
   "description": "Threshold:\nWarning: 5M\nCritical:  10M",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"dev-ingest-router-group\", job=\"ingestion-kafka-exporter\", topic=\"prod.telemetry.ingestion\"})"
    }
   ]
  },
  {
   "title": "Telemetry Extractor lag",
   "type": "graph",
   "description": "Threshold:\nWarning: 5M\nCritical:  10M",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"dev-telemetry-extractor-group\", job=\"processing-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "PreProcessor lag",
   "type": "graph",
   "description": "Threshold:\nWarning: 5M\nCritical:  10M",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"dev-pipeline-preprocessor-group\", job=\"processing-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "DenormalizationPrimary lag",
   "type": "graph",
   "description": "Threshold:\nWarning: 5M\nCritical:  10M",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"dev-telemetry-denorm-primary-group\", job=\"processing-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "DenormalizationSecondary lag",
   "type": "graph",
   "description": "Threshold:\nWarning: 5M\nCritical:  10M",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"dev-telemetry-denorm-secondary-group\", job=\"processing-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "SummaryDenorm lag",
   "type": "graph",
   "description": "Threshold:\nWarning: 5M\nCritical:  10M",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"dev-summmary-denorm-group\", job=\"processing-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "DruidValidator lag",
   "type": "graph",
   "description": "Threshold:\nWarning: 5M\nCritical:  10M",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"dev-druid-validator-group\", job=\"processing-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "assessment aggregator lag",
   "type": "graph",
   "description": "Threshold:\nWarning: 5M\nCritical:  10M",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"dev-assessment-aggregator-group\", job=\"processing-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "Rating lag",
   "type": "graph",
   "description": "Threshold:\nWarning: 5M\nCritical:  10M",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"dev-rating-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "UserCacheUpdaterV2 lag",
   "type": "graph",
   "description": "Threshold:\nWarning: 5M\nCritical:  10M",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"dev-user-cache-updater-consumer-group\", job=\"processing-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "ContentCacheUpdater lag",
   "type": "graph",
   "description": "Threshold:\nWarning: 5M\nCritical:  10M",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"dev-content-cache-updater-group\", job=\"ingestion-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "device profile updater lag",
   "type": "graph",
   "description": "Threshold:\nWarning: 5M\nCritical:  10M",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"dev-device-profile-updater-group\", job=\"processing-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "cb-preprocessor lag",
   "type": "graph",
   "description": "Threshold:\nWarning: 5M\nCritical:  10M",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"dev-cb-preprocessor-group\", job=\"processing-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "Error Denorm lag",
   "type": "graph",
   "description": "Threshold:\nWarning: 5M\nCritical:  10M",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"dev-error-denorm-group\", job=\"processing-kafka-exporter\"})"
    }
   ]
  },
  {
   "title": "Secor Lag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 },
   "collapsed": true,
   "panels": [
    {
     "title": "raw-telemetry-backup",
     "type": "graph",
     "description": "Threshold: \nWarning: 10M\nCritical: 15M",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=\"prod.telemetry.raw.backup\", job=\"processing-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "failed-telemetry-backup",
     "type": "graph",
     "description": "Threshold: \nWarning: 15M\nCritical: 20M",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=\"prod.telemetry.failed.backup\", job=\"processing-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "unique-telemetry-backup",
     "type": "graph",
     "description": "Threshold: \nWarning: 1M\nCritical: 2M",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=\"prod.telemetry.unique.backup\", job=\"processing-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "channel-telemetry-backup",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 1M\nCritical: 2M",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 53 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kafka_consumergroup_lag_sum{consumergroup=~\"$env.telemetry.channel.backup\", job=\"processing-kafka-exporter\"}"
      }
     ]
    },
    {
     "title": "denorm-events-backup",
     "type": "graph",
     "description": "Threshold: \nWarning: 15M\nCritical: 20M",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=\"prod.telemetry.denorm.backup\", job=\"processing-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "derived-denorm-events-backup",
     "type": "graph",
     "description": "Threshold: \nWarning: 15M\nCritical: 20M",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=\"prod.summary.backup\", job=\"processing-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "channel-summary-backup",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 1M\nCritical: 2M",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 57 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kafka_consumergroup_lag_sum{consumergroup=~\"$env.summary.channel.backup\", job=\"processing-kafka-exporter\"}"
      }
     ]
    },
    {
     "title": "extractor-failed-backup",
     "type": "graph",
     "description": "Threshold: \nWarning: 1M\nCritical: 2M",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=\"prod.extractor.failed.backup\", job=\"processing-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "assess-raw-events-backup",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 15M\nCritical: 20M",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 57 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kafka_consumergroup_lag_sum{consumergroup=~\"$env.telemetry.assess.raw\", job=\"processing-kafka-exporter\"}"
      }
     ]
    },
    {
     "title": "telemetry-duplicate-backup",
     "type": "graph",
     "description": "Threshold: \nWarning: 15M\nCritical: 20M",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=\"prod.telemetry.duplicate.backup\", job=\"processing-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "extractor-duplicate-backup",
     "type": "graph",
     "description": "Threshod: \nWarning: 50K\nCritical: 1L",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=\"prod.extractor.duplicate.backup\", job=\"processing-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "ingestion-telemetry-backup",
     "type": "graph",
     "description": "Threshold: \nWarning: 15M\nCritical: 20M",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=\"prod.telemetry.ingestion.events.backup\", job=\"ingestion-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "derived-telemetry-backup",
     "type": "graph",
     "description": "Threshold: \nWarning: 1M\nCritical: 2M",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=\"prod.telemetry.derived.unique.backup\", job=\"processing-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "device-profile-backup",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 1M\nCritical: 2M",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 61 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kafka_consumergroup_lag_sum{consumergroup=~\"$env.events.device.profile.backup\", job=\"ingestion-kafka-exporter\"}"
      }
     ]
    },
    {
     "title": " learning-events-backup",
     "type": "graph",
     "description": "Threshold: \nWarning: 1M\nCritical: 2M",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=\"prod.learning.graph.events.backup\", job=\"ingestion-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "learning-failed-backup",
     "type": "graph",
     "description": "Threshold: \nWarning: 15M\nCritical: 20M",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=\"prod.failed.learning.events.backup\", job=\"ingestion-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "assess-events-backup",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 1M\nCritical: 1.5M",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 61 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kafka_consumergroup_lag_sum{consumergroup=~\"$env.telemetry.assess.events.backup\", job=\"ingestion-kafka-exporter\"}"
      }
     ]
    },
    {
     "title": "issue-certificate-events-backup",
     "type": "graph",
     "description": "Threshold: \nWarning: 4M\nCritical: 8M",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=\"prod.issue.certificate.request.backup\", job=\"ingestion-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "content-consumption-events-backup",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 1M\nCritical: 1.5M",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 65 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kafka_consumergroup_lag_sum{consumergroup=~\"$env.coursebatch.job.request.backup\", job=\"ingestion-kafka-exporter\"}"
      }
     ]
    },
    {
     "title": "error-telemetry-backup",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 1M\nCritical: 1.5M",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 65 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kafka_consumergroup_lag_sum{consumergroup=~\"$env.druid.events.error.backup\", job=\"processing-kafka-exporter\"}"
      }
     ]
    },
    {
     "title": "content-auto-creation-events-backup",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 1M\nCritical: 1.5M",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 65 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kafka_consumergroup_lag_sum{consumergroup=~\"$env.auto.creation.job.request.backup\", job=\"ingestion-kafka-exporter\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "WFS Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Data Products time taken",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(dataproduct_workflowsummarymodel_time_taken_secs)",
       "legendFormat": "time_taken: {{ subsystem }}"
      }
     ]
    },
    {
     "title": "Total Data Products Input count",
     "type": "table",
     "gridPos": { "h": 5, "w": 11, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(sum_over_time(dataproduct_workflowsummarymodel_input_events[${__range_s}s])) by (report_date)",
       "legendFormat": "input_events"
      }
     ]
    },
    {
     "title": "Total Data Products Output count",
     "type": "table",
     "gridPos": { "h": 5, "w": 13, "x": 11, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(sum_over_time(dataproduct_workflowsummarymodel_output_events[${__range_s}s])) by (report_date)",
       "legendFormat": "input_events"
      }
     ]
    }
   ]
  },
  {
   "title": "Druid Raw Cluster DataSource Lag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 },
   "collapsed": true,
   "panels": [
    {
     "title": "Summary-Events",
     "type": "singlestat",
     "description": "DataSource name: summary-events",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_ingest_kafka_lag{cluster=\"raw\",exported_job=\"summary-events\"}"
      }
     ]
    },
    {
     "title": "TelemetryEventsSyncts",
     "type": "singlestat",
     "description": "Datasource name: telemetry-events-syncts",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_ingest_kafka_lag{cluster=\"raw\",exported_job=\"telemetry-events-syncts\"}"
      }
     ]
    },
    {
     "title": "TelemetryFeedbackEvents",
     "type": "singlestat",
     "description": "Datasource name:  telemetry-feedback-events",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_ingest_kafka_lag{cluster=\"raw\",exported_job=\"telemetry-feedback-events\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Druid Raw Cluster Segment Unavailable Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 },
   "collapsed": true,
   "panels": [
    {
     "title": "ContentModelSnapshot",
     "type": "singlestat",
     "description": "Threshold:\nCritical: 1",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_segment_unavailable_count{cluster=\"raw\",exported_job=\"content-model-snapshot\"}"
      }
     ]
    },
    {
     "title": "OfflineDesktopEvents",
     "type": "singlestat",
     "description": "Threshold:\nCritical: 1",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_segment_unavailable_count{cluster=\"raw\",exported_job=\"offline-desktop-events\"}"
      }
     ]
    },
    {
     "title": "PipelineMetrics",
     "type": "singlestat",
     "description": "Threshold:\nCritical: 1",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_segment_unavailable_count{cluster=\"raw\",exported_job=\"pipeline-metrics\"}"
      }
     ]
    },
    {
     "title": "SummaryEvents",
     "type": "singlestat",
     "description": "Threshold:\nCritical: 1",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_segment_unavailable_count{cluster=\"raw\",exported_job=\"summary-events\"}"
      }
     ]
    },
    {
     "title": "TelemetryErrorEvents",
     "type": "singlestat",
     "description": "Threshold:\nCritical: 1",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_segment_unavailable_count{cluster=\"raw\",exported_job=\"telemetry-error-events\"}"
      }
     ]
    },
    {
     "title": "TelemetryEvents",
     "type": "singlestat",
     "description": "Threshold:\nCritical: 1",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_segment_unavailable_count{cluster=\"raw\",exported_job=\"telemetry-events\"}"
      }
     ]
    },
    {
     "title": "TelemetryEventsSyncts",
     "type": "singlestat",
     "description": "Threshold:\nCritical: 1",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_segment_unavailable_count{cluster=\"raw\",exported_job=\"telemetry-events-syncts\"}"
      }
     ]
    },
    {
     "title": "TelemetryFeedbackEvents",
     "type": "singlestat",
     "description": "Threshold:\nCritical: 1",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 20 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_segment_unavailable_count{cluster=\"raw\",exported_job=\"telemetry-feedback-events\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Secor Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 },
   "collapsed": true,
   "panels": [
    {
     "title": "derived-telemetry-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"derived-telemetry-.+\"})"
      }
     ]
    },
    {
     "title": "derived-denorm-events-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"derived-denorm-events-.+\"})"
      }
     ]
    },
    {
     "title": "channel-summary-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"channel-summary-.+\"})"
      }
     ]
    },
    {
     "title": "assess-events-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"assess-events-.+\"})"
      }
     ]
    },
    {
     "title": "assess-raw-events-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"assess-raw-events-.+\"})"
      }
     ]
    },
    {
     "title": "device-profile-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"device-profile-.+\"})"
      }
     ]
    },
    {
     "title": "learning-events-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"learning-events-.+\"})"
      }
     ]
    },
    {
     "title": "learning-failed-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"learning-failed-.+\"})"
      }
     ]
    },
    {
     "title": "content-consumption-events-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"content-consumption-events-.+\"})"
      }
     ]
    },
    {
     "title": "failed-telemetry-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"failed-telemetry-.+\"})"
      }
     ]
    },
    {
     "title": "extractor-duplicate-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"extractor-duplicate-.+\"})"
      }
     ]
    },
    {
     "title": "extractor-failed-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"extractor-failed-.+\"})"
      }
     ]
    },
    {
     "title": "channel-telemetry-backup",
     "type": "singlestat",
     "description": "Expected running process count: 8",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"channel-telemetry-backup-.+\"})"
      }
     ]
    },
    {
     "title": "raw-telemetry-backup",
     "type": "singlestat",
     "description": "Expected running process count: 8",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 19 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"raw-telemetry-backup-.+\"})"
      }
     ]
    },
    {
     "title": "ingestion-telemetry-backup",
     "type": "singlestat",
     "description": "Expected running process count: 4",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 19 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"ingestion-telemetry-backup-.+\"})"
      }
     ]
    },
    {
     "title": "denorm-events-backup",
     "type": "singlestat",
     "description": "Expected running process count: 8",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 19 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"denorm-events-backup-.+\"})"
      }
     ]
    },
    {
     "title": "unique-telemetry-backup",
     "type": "singlestat",
     "description": "Expected running process count: 8",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 19 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"unique-telemetry-backup-.+\"})"
      }
     ]
    }
   ]
  }
 ]
}