- hosts: es-backup
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  vars:
    - es_snapshot_host: "{{app_es_snapshot_host}}"
    - snapshot_base_path: "{{app_snapshot_base_path}}"
  roles:
    - role: es-s3-snapshot
  tags:
    - es_backup
  run_once: true
